version: '2'
services:
  shadowsocks:
    image: mritd/shadowsocks
    container_name: shadowsocks
    restart: always
    ports:
      - 6443:6443
      - 6500:6500/udp
    environment:
      SS_CONFIG: "-s 0.0.0.0 -p 6443 -m chacha20 -k password --fast-open"
      KCP_MODULE: "kcpserver"
      KCP_CONFIG: "-t 127.0.0.1:6443 -l :6500 -mode fast2"
      KCP_FLAG: "true"
