apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: echo-header
          servicePort: 8080
