apiVersion: apps/v1beta2
kind: Deployment
metadata:
  generation: 1
  labels:
    app: echo-header
  name: echo-header
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-header
  template:
    metadata:
      labels:
        app: echo-header
    spec:
      containers:
        - image: 'brndnmtthws/nginx-echo-headers:latest'
          imagePullPolicy: Always
          name: echo-header
      restartPolicy: Always
