apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8dash
  namespace: kube-system
spec:
  rules:
    - host: test-k3s.gllue.net
      http:
        paths:
          - backend:
              serviceName: k8dash
              servicePort: 80
            path: /